simplestNetworkSim_covidAdapted.py
Raise exceptions on malformed input, or missing parameters.
=> Fixes to reading input

sample_input_files/data_dictionary.txt
Should aid in prepping code to ingest them. I'm aware that these will be deprecated by the move to HDF5, but I need them working now with what we have so I can do development model runs.
=> created basic data dictionary for current data input file sample formats

simplestNetworkSim_covidAdapted.py
Resolves ScottishCovidResponse/SCRCIssueTracking#190
=> tagged functions as in use or not in use

simplestNetworkSim_covidAdapted.py
Added a really basic time series reporting function, should let me start plotting/checking realisticness.
Resolves ScottishCovidResponse/SCRCIssueTracking#201
=> added basic reporting function

simple_network_sim/network_of_populations.py, tests/unit/test_network_of_populations.py
I didn't do any changes that would affect the final result yet (the regression is still passing unmodified), however I did add a few asserts (reasoning being that it's better to fail than to produce the wrong result). I've also refactored some of the code in doBetweenInfectionAgeStructured into its own function so that it's easier to test.
=> Create more unit tests

.travis.yml
This runs all the tests in a Conda environment (the one from
spec-file.txt), and uploads coverage reports to codecov.io
Closes: SCRC-137
Signed-off-by: William Pettersson <william.pettersson@glasgow.ac.uk>
=> Travis CI file

README.md, contributing.md
Resolves https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/257.
=> Review and update readme

simple_network_sim/loaders.py
Replaces PR #38 due to problems with git history on that branch. Addresses reviewer comments on PR #38.
=> Document loaders

data_sources.md, data_wishlist_plans
Resolves https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/240. 
Ultimately this file may need to be removed in favour of a description of how we interact with data infrastructure (in fact, it could perhaps be removed now?). For the time being however, I favour developing it into an accessible list of where we get our data and parameters form. This might be useful to the data team.
=> basic data source info

simple_network_sim/common.py, simple_network_sim/network_of_populations.py, simple_network_sim/sampleUseOfModel.py, tests/unit/test_network_of_populations.py
Refactor a bit the main function to be able to call run_simulation from a notebook too.
=> Issue #295 Issue #300 - Add docstring to common and sampleUseOfModel. 

simple_network_sim/network_of_populations.py, simple_network_sim/sampleUseOfModel.py, tests/unit/test_network_of_populations.py
I've converted a few parameters to use comma separated list, instead of space separated. That makes it easier to parse subcommands after such arguments.
Closes: https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/412
=> Parametrise list of infectious people

tests/utils.py
Resolves https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/496
=> Some tests failing on Windows 10

simple_network_sim/loaders.py, simple_network_sim/network_of_populations/__init__.py, simple_network_sim/sampleUseOfModel.py, tests/unit/test_loaders.py, tests/unit/test_network_of_populations/test_init.py
=> Draft of adding stochasticity

README.md, contributing.md
Various problems with github and travis have caused me to re-make this PR. Supersedes https://github.com/ScottishCovidResponse/simple_network_sim/pull/69
=> How to build docs locally (re-done PR)

README.md, simple_network_sim/network_of_individuals.py, simple_network_sim/network_of_populations/report.py
Resolves https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/567
=> More detailed docs on testing

.pylintrc
This means we're publicly specifying linter settings.
=> Add pylint config file for codacy

extractors/test_comix_downsampler.py, simple_network_sim/common.py, simple_network_sim/loaders.py, simple_network_sim/network_of_populations/__init__.py, simple_network_sim/sampleUseOfModel.py, tests/conftest.py, tests/unit/test_csv_to_hdf5.py, tests/unit/test_loaders.py, tests/unit/test_network_of_populations/test_init.py
Closes: https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/593
I have fixed the trivial ones and told pylint to ignore the things I thought were not valid complaints. I have created this ticket for something that'd take longer to fix (and I'm not entirely sure if we care): https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/633
The code duplication in actual code is 0. Codacy complains about code duplication in tests, but I consider code duplication in tests good practice.
=> Placate codacy

simple_network_sim/network_of_populations/__init__.py, tests/unit/test_network_of_populations/test_init.py
https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/679
=> Issue 679 - Ensure all random numbers are generated consistently

environment.yml, simple_network_sim/sampleUseOfModel.py, spec-file.txt, tests/conftest.py
This PR resolves https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/660.
=> Support data pipeline API v0.7.0 (breaking change)

doc/scenario_plans/scenario_plans.md
This is a few general suggestions/examples for how we might adjust the simple network sim inputs in future to model a few example scenarios.  
As in https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/685
=> adding a few example scenario modelling plans

environment.yml, spec-file.txt, tests/regression/test_network_of_populations.py
Also fixes some tests on Windows.
=> Data api v0.7.2

extractors/generating_sns_products/aggregate_flows_from_google_data.py, extractors/generating_sns_products/data_processing_config.yaml, extractors/generating_sns_products/metadata.yaml
To simplify things, I started a new branch, moved ant's work form issue-700 over here, added to the config files in this branch, updated things to work with the newer data_pipeline_api, and removed the last of the downloading in the movement modifier generating script.
=> Amended movement modifiers - issue 700
